### ISSUE TITLE
Constant -- XCONST

### ISSUE THREAD

**Issue by standbyme** [standbyme/jvm-rs#16]
Refer to [jvm.go/instructions/constants/xconst.go](https://github.com/zxh0/jvm.go/blob/master/jvmgo/instructions/constants/xconst.go)
ACONST_NULL will be added to this issue after #13 is finished.
- [x] DCONST_0
- [x] DCONST_1
- [x] FCONST_0
- [x] FCONST_1
- [x] FCONST_2
- [x] ICONST_M1
- [x] ICONST_0
- [x] ICONST_1
- [x] ICONST_2
- [x] ICONST_3
- [x] ICONST_4
- [x] ICONST_5
- [x] LCONST_0
- [x] LCONST_1

**Comment by SwapnilBhosale** [comment]
I will add remaining instructions.
