### ISSUE TITLE
Parse ClassFile

### ISSUE THREAD

**Issue by standbyme** [standbyme/jvm-rs#2]
[The Constant Pool](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4)
# ConstantInfo
- [x] [UTF8](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.7)
- [x] [INTEGER](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.4)
- [x] [FLOAT](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.4)
- [x] [LONG](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.5)
- [x] [DOUBLE](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.5)
- [x] [CLASS](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.1)
- [x] [STRING](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.3)
- [x] [METHODREF](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.2)
- [x] [NAME_AND_TYPE](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.6)
- [x] [INTERFACE_METHODREF](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.2)
# AttributeInfo
- [x] [Deprecated](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.15)
- [x] [Synthetic](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.8)
- [x] [SourceFile](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.10)
- [x] [ConstantValue](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.2)
- [x] [Code](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.3)
- [x] [Exceptions](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.5)
- [x] [LineNumberTable](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.12)
- [x] [LocalVariableTable](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.13)

**Comment by SwapnilBhosale** [comment]
Can you please attach  link for jvm specs for the issue?

**Comment by standbyme** [comment]
@SwapnilBhosale Thanks!
I'm doing it. You can see it later.

**Comment by SwapnilBhosale** [comment]
Thanks for the update. I will check the doc and will update if I can take up this issue.

**Comment by standbyme** [comment]
😆

**Comment by standbyme** [comment]
@SwapnilBhosale 
I wrote some comments that might be helpful.
Welcome PR : )
