### ISSUE TITLE
Math -- MUL

### ISSUE THREAD

**Issue by standbyme** [standbyme/jvm-rs#24]
Refer to [jvm.go/instructions/instructions/math/mul](https://github.com/zxh0/jvm.go/blob/master/jvmgo/instructions/math/mul.go)

- [x] DMUL
- [x] FMUL
- [x] IMUL
- [x] LMUL

**Comment by SwapnilBhosale** [comment]
I will work on it

**Comment by standbyme** [comment]
Thanks 😄

**Comment by standbyme** [comment]
Finished
