### ISSUE TITLE
Math -- NEG

### ISSUE THREAD

**Issue by standbyme** [standbyme/jvm-rs#25]
Refer to [jvm.go/instructions/instructions/math/neg](https://github.com/zxh0/jvm.go/blob/master/jvmgo/instructions/math/neg.go)

- [ ] DNEG
- [ ] FNEG
- [ ] INEG
- [ ] LNEG

**Comment by abhijeetbhagat** [comment]
I will take this

**Comment by standbyme** [comment]
Thanks
😆
