### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by standbyme** [standbyme/jvm-rs#9]
Refer to [jvm.go/instructions/comparisons](https://github.com/zxh0/jvm.go/blob/master/jvmgo/instructions/comparisons)
- [x] dcmp
  - [x] _dcmp
  - [x] DCMPG
  - [x] DCMPL
- [x] fcmp
  - [x] _fcmp
  - [x] FCMPG
  - [x] FCMPL
- [x] LCMP
- [x] if_icmp
  - [x] _icmpPop
  - [x] IF_ICMPEQ
  - [x] IF_ICMPNE
  - [x] IF_ICMPLT
  - [x] IF_ICMPLE
  - [x] IF_ICMPGT
  - [x] IF_ICMPGE
- [x] ifcond
  - [x] IFEQ
  - [x] IFNE
  - [x] IFLT
  - [x] IFLE
  - [x] IFGT
  - [x] IFGE

**Comment by SwapnilBhosale** [comment]
I will be working on if_icmp instructions

**Comment by SwapnilBhosale** [comment]
Created PR for DCMP instruction

**Comment by abhijeetbhagat** [comment]
I can implement `fcmp`

**Comment by standbyme** [comment]
Add LCMP

**Comment by standbyme** [comment]
Add ifcond

**Comment by abhijeetbhagat** [comment]
@standbyme i think you mean `if_icmp` and `dcmp`. I can take up `lcmp`.

**Comment by standbyme** [comment]
@abhijeetbhagat YES,it's dcmp, I have corrected it.😅
Thank you!

**Comment by SwapnilBhosale** [comment]
I will add test cases.

**Comment by SwapnilBhosale** [comment]
I working on ifcond.

**Comment by standbyme** [comment]
Finished 😆

**Comment by standbyme** [comment]
@SwapnilBhosale Please check #20 😆

**Comment by SwapnilBhosale** [comment]
corrected the test cases and created PR #30
